# Generated by Django 4.1.9 on 2023-05-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TranstactionID', models.AutoField(primary_key=True, serialize=False)),
                ('ClientID', models.CharField(max_length=12)),
                ('EmployeeID', models.CharField(max_length=12)),
                ('Payment_Method', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=500)),
                ('Surname', models.CharField(max_length=500)),
                ('UserType', models.CharField(max_length=500)),
            ],
        ),
    ]
