# Generated by Django 4.1.9 on 2023-05-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('OperationID', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeID', models.CharField(max_length=512)),
                ('ClientID', models.CharField(max_length=512)),
                ('EquipmentID', models.CharField(max_length=512)),
                ('TransactionID', models.CharField(max_length=512)),
            ],
        ),
    ]
