# Generated by Django 4.1.9 on 2023-06-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_shop', '0002_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('EquipmentID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ServiceID', models.AutoField(primary_key=True, serialize=False)),
                ('ClientID', models.CharField(max_length=512)),
                ('EmployeeID', models.CharField(max_length=512)),
                ('TransactionID', models.CharField(max_length=512)),
                ('ServiceType', models.CharField(max_length=512)),
            ],
        ),
    ]
