# Generated by Django 4.1.9 on 2023-06-02 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ski_shop', '0003_equipment_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='TranstactionID',
            new_name='TransactionID',
        ),
    ]
