# Generated by Django 4.1.9 on 2023-06-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_shop', '0004_rename_transtactionid_transaction_transactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='OperationEnd',
            field=models.CharField(default='00.00.0000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='OperationStart',
            field=models.CharField(default='00.00.0000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='Amount',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
