# Generated by Django 4.1.9 on 2023-06-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ski_shop', '0005_operation_operationend_operation_operationstart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Payment_Method',
            new_name='Payment',
        ),
    ]
