# Generated by Django 4.1.9 on 2023-06-03 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ski_shop', '0006_rename_payment_method_transaction_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Transaction1',
        ),
    ]
