# Generated by Django 4.1.9 on 2023-06-03 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ski_shop', '0007_rename_transaction_transaction1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction1',
            new_name='Transaction',
        ),
    ]
