# Generated by Django 4.1.9 on 2023-06-03 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ski_shop', '0008_rename_transaction1_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='TransactionID',
            new_name='ZmianaID',
        ),
    ]
