# Generated by Django 4.1.9 on 2023-06-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_shop', '0009_rename_transactionid_transaction_zmianaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('ClientID', models.CharField(max_length=12)),
                ('EmployeeID', models.CharField(max_length=12)),
                ('Amount', models.CharField(max_length=12)),
                ('PaymentType', models.CharField(max_length=500)),
            ],
        ),
    ]
