# Generated by Django 4.1.9 on 2023-06-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_shop', '0010_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='equipment',
            name='EquipmentDESC',
            field=models.JSONField(default={''}),
        ),
    ]
