# Generated by Django 4.1.9 on 2023-06-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_shop', '0011_delete_transaction_equipment_equipmentdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='EquipmentType',
            field=models.CharField(default='Narty', max_length=512),
            preserve_default=False,
        ),
    ]
